-- MySQL Script generated by MySQL Workbench
-- 08/23/16 12:25:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemon` (
  `idPokemon` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `peso` DECIMAL(4,2) NULL,
  `Ataque` INT NOT NULL,
  `Defesa` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  `Pokemon_idPokemon` INT NOT NULL,
  PRIMARY KEY (`idPokemon`, `Tipo_idTipo`),
  INDEX `fk_Pokemon_Tipo_idx` (`Tipo_idTipo` ASC),
  INDEX `fk_Pokemon_Pokemon1_idx` (`Pokemon_idPokemon` ASC),
  CONSTRAINT `fk_Pokemon_Tipo`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localizacao` (
  `idLocalizacao` INT NOT NULL AUTO_INCREMENT,
  `Local` VARCHAR(45) NOT NULL,
  `Latitude` DECIMAL(2,5) NOT NULL,
  `Longitude` DECIMAL(3,5) NOT NULL,
  PRIMARY KEY (`idLocalizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pokemon_has_Localizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pokemon_has_Localizacao` (
  `Pokemon_idPokemon` INT NOT NULL,
  `Localizacao_idLocalizacao` INT NOT NULL,
  PRIMARY KEY (`Pokemon_idPokemon`, `Localizacao_idLocalizacao`),
  INDEX `fk_Pokemon_has_Localizacao_Localizacao1_idx` (`Localizacao_idLocalizacao` ASC),
  INDEX `fk_Pokemon_has_Localizacao_Pokemon1_idx` (`Pokemon_idPokemon` ASC),
  CONSTRAINT `fk_Pokemon_has_Localizacao_Pokemon1`
    FOREIGN KEY (`Pokemon_idPokemon`)
    REFERENCES `mydb`.`Pokemon` (`idPokemon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pokemon_has_Localizacao_Localizacao1`
    FOREIGN KEY (`Localizacao_idLocalizacao`)
    REFERENCES `mydb`.`Localizacao` (`idLocalizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
